#
#  Copyright 2026 The InfiniFlow Authors. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
import logging
import json
import re

import oracledb as oracle
from peewee import (
    CharField,
    Database,
    ImproperlyConfigured,
    InterfaceError,
    IntegrityError,
    DataError,
    DatabaseError,
    InternalError,
    NotSupportedError,
    OperationalError,
    ProgrammingError,
)
from playhouse.migrate import SchemaMigrator
from playhouse.pool import PooledDatabase


logger = logging.getLogger("ragflow.oracle_ext")
logger.setLevel(logging.DEBUG)


def _summarize_log_params(params):
    if not params:
        return params
    if isinstance(params, dict):
        items = params.items()
    else:
        items = ((f":{idx}", value) for idx, value in enumerate(params, start=1))

    summarized = {}
    for key, value in items:
        if isinstance(value, str) and len(value) > 256:
            summarized[key] = f"{value[:256]}...({len(value)} chars)"
        elif isinstance(value, (list, tuple)) and len(value) > 16:
            summarized[key] = f"<{type(value).__name__} len={len(value)}>"
        else:
            summarized[key] = value
    return summarized


def _bind_sequence_params(sql, params):
    bind_params = {}
    placeholder_index = 1
    while ":%d" in sql:
        bind_name = f"p{placeholder_index}"
        sql = sql.replace(":%d", f":{bind_name}", 1)
        bind_params[bind_name] = params[placeholder_index - 1]
        placeholder_index += 1
    return sql, bind_params


class ExceptionWrapper:
    __slots__ = ("exceptions",)

    def __init__(self, exceptions):
        self.exceptions = exceptions

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type is None:
            return False
        if exc_type.__name__ in self.exceptions:
            raise self.exceptions[exc_type.__name__](exc_value)
        return False


EXCEPTIONS = {
    "ConstraintError": IntegrityError,
    "DatabaseError": DatabaseError,
    "DataError": DataError,
    "IntegrityError": IntegrityError,
    "InterfaceError": InterfaceError,
    "InternalError": InternalError,
    "NotSupportedError": NotSupportedError,
    "OperationalError": OperationalError,
    "ProgrammingError": ProgrammingError,
    "TransactionRollbackError": OperationalError,
    "UndefinedFunction": ProgrammingError,
    "UniqueViolation": IntegrityError,
}

__exception_wrapper__ = ExceptionWrapper(EXCEPTIONS)


class OracleDatabase(Database):
    # 定制开发：Wanbo 20250415
    safe_create_index = False
    field_types = {
        "AUTO": "NUMBER GENERATED BY DEFAULT AS IDENTITY",
        "BIGAUTO": "NUMBER GENERATED BY DEFAULT AS IDENTITY",
        "BOOL": "NUMBER(1)",
        "DECIMAL": "NUMBER",
        "DOUBLE": "BINARY_DOUBLE",
        "FLOAT": "BINARY_FLOAT",
        "INT": "NUMBER(11)",
        "BIGINT": "NUMBER(19)",
        "SMALLINT": "NUMBER(4)",
        "VARCHAR": "VARCHAR2",
        "TEXT": "CLOB",
        "JSON": "CLOB",
        "DATETIME": "TIMESTAMP",
        "DATE": "DATE",
        "TIME": "TIMESTAMP",
        "BLOB": "BLOB",
        "UUID": "VARCHAR2(32)",
        "UUIDB": "RAW(16)",
    }
    operations = {
        "LIKE": "LIKE",
        "ILIKE": "LIKE",
        "REGEXP": "REGEXP_LIKE",
        "IREGEXP": "REGEXP_LIKE",
        "BETWEEN": "BETWEEN",
        "MATCH": "LIKE",
        "XOR": "XOR",
    }
    param = ":%d"

    def _connect(self):
        if oracle is None:
            raise ImproperlyConfigured("oracledb is required.")

        user = self.connect_params.get("user")
        password = self.connect_params.get("password")
        db = self.connect_params.get("db", self.database)
        host = self.connect_params.get("host")
        port = self.connect_params.get("port", 1521)

        if not all([user, password, host, port, db]):
            raise ImproperlyConfigured("Oracle connection config is incomplete.")

        dsn = f"{host}:{port}/{db}"
        logger.debug("OracleDatabase._connect dsn=%s user=%s", dsn, user)
        return oracle.connect(user=user, password=password, dsn=dsn)

    def _placeholder(self, idx):
        return f":{idx}"

    def quote_char(self):
        return '"'

    def get_binary_type(self):
        return oracle.BLOB

    def get_tables(self, schema=None):
        query = "SELECT table_name FROM all_tables WHERE owner = :owner ORDER BY table_name"
        owner = (schema or self.connect_params.get("user") or "").upper()
        with __exception_wrapper__:
            cursor = self.execute_sql(query, {"owner": owner})
            return [row[0] for row in cursor.fetchall()]

    def begin(self):
        if self.is_closed():
            self.connect()
        with __exception_wrapper__:
            self.cursor().execute("BEGIN NULL; END;")

    def rollback(self):
        with __exception_wrapper__:
            self.cursor().connection.rollback()

    def commit(self):
        with __exception_wrapper__:
            self.cursor().connection.commit()

    def execute_sql(self, sql, params=None, commit=None):
        if params and isinstance(params, (list, tuple)):
            sql, params = _bind_sequence_params(sql, params)

        sql = self._rewrite_source_aliases(sql)
        sql = self._rewrite_limit_clause(sql)
        cursor = self.cursor()
        try:
            logger.debug(
                "OracleDatabase.execute_sql sql=%s params=%s commit=%s",
                sql,
                _summarize_log_params(params),
                commit,
            )
            cursor.execute(sql, params or ())
            if commit or sql.lstrip().upper().startswith(("INSERT", "UPDATE", "DELETE", "MERGE", "ALTER", "CREATE", "DROP")):
                cursor.connection.commit()
        except oracle.Error as ex:
            logger.exception("Oracle execute_sql failed: %s", sql)
            raise ex
        return cursor

    @staticmethod
    def _rewrite_limit_clause(sql: str) -> str:
        # 定制开发：Wanbo 20250415
        if not re.search(r"\bLIMIT\b", sql, flags=re.IGNORECASE):
            return sql

        pattern = re.compile(
            r"LIMIT\s+(?P<limit>:[A-Za-z_][A-Za-z0-9_]*|:\d+|\d+)(?:\s*,\s*(?P<offset>:[A-Za-z_][A-Za-z0-9_]*|:\d+|\d+)|\s+OFFSET\s+(?P<offset2>:[A-Za-z_][A-Za-z0-9_]*|:\d+|\d+))?",
            flags=re.IGNORECASE,
        )
        match = pattern.search(sql)
        if not match:
            return sql

        limit = match.group("limit")
        offset = match.group("offset") or match.group("offset2")
        if offset:
            replacement = f"OFFSET {offset} ROWS FETCH NEXT {limit} ROWS ONLY"
        else:
            replacement = f"FETCH FIRST {limit} ROWS ONLY"
        return sql[: match.start()] + replacement + sql[match.end() :]

    @classmethod
    def _rewrite_source_aliases(cls, sql: str) -> str:
        pattern = re.compile(r"\b(?:FROM|JOIN)\b", flags=re.IGNORECASE)
        rewritten = []
        cursor = 0

        while True:
            match = pattern.search(sql, cursor)
            if match is None:
                rewritten.append(sql[cursor:])
                return "".join(rewritten)

            rewritten.append(sql[cursor:match.end()])
            idx = match.end()

            while idx < len(sql) and sql[idx].isspace():
                idx += 1
            rewritten.append(sql[match.end():idx])

            source_start = idx
            source_end = cls._consume_source(sql, source_start)
            if source_start < len(sql) and sql[source_start] == "(":
                inner_sql = sql[source_start + 1:source_end - 1]
                rewritten.append("(")
                rewritten.append(cls._rewrite_source_aliases(inner_sql))
                rewritten.append(")")
            else:
                rewritten.append(sql[source_start:source_end])

            alias_prefix = source_end
            while alias_prefix < len(sql) and sql[alias_prefix].isspace():
                alias_prefix += 1

            alias_token = sql[alias_prefix:alias_prefix + 2]
            if alias_token.upper() == "AS" and cls._is_word_boundary(sql, alias_prefix + 2):
                alias_start = alias_prefix + 2
                while alias_start < len(sql) and sql[alias_start].isspace():
                    alias_start += 1

                alias_end = cls._consume_alias(sql, alias_start)
                if alias_end > alias_start:
                    rewritten.append(" ")
                    rewritten.append(sql[alias_start:alias_end])
                    cursor = alias_end
                    continue

            cursor = source_end

    @staticmethod
    def _consume_source(sql: str, start: int) -> int:
        if start >= len(sql):
            return start

        if sql[start] != "(":
            end = start
            while end < len(sql) and not sql[end].isspace():
                end += 1
            return end

        depth = 0
        in_single_quote = False
        in_double_quote = False
        idx = start

        while idx < len(sql):
            char = sql[idx]

            if char == "'" and not in_double_quote:
                if in_single_quote and idx + 1 < len(sql) and sql[idx + 1] == "'":
                    idx += 2
                    continue
                in_single_quote = not in_single_quote
            elif char == '"' and not in_single_quote:
                in_double_quote = not in_double_quote
            elif not in_single_quote and not in_double_quote:
                if char == "(":
                    depth += 1
                elif char == ")":
                    depth -= 1
                    if depth == 0:
                        return idx + 1

            idx += 1

        return len(sql)

    @staticmethod
    def _consume_alias(sql: str, start: int) -> int:
        if start >= len(sql):
            return start

        if sql[start] == '"':
            end = start + 1
            while end < len(sql):
                if sql[end] == '"':
                    return end + 1
                end += 1
            return len(sql)

        if not OracleDatabase._is_identifier_char(sql[start], allow_digit=False):
            return start

        end = start + 1
        while end < len(sql) and OracleDatabase._is_identifier_char(sql[end], allow_digit=True):
            end += 1
        return end

    @staticmethod
    def _is_identifier_char(char: str, allow_digit: bool) -> bool:
        return char.isalpha() or char in ("_", "$", "#") or (allow_digit and char.isdigit())

    @staticmethod
    def _is_word_boundary(sql: str, idx: int) -> bool:
        if idx >= len(sql):
            return True
        return not OracleDatabase._is_identifier_char(sql[idx], allow_digit=True)


class PooledOracleDatabase(PooledDatabase, OracleDatabase):
    # 定制开发：Wanbo 20250415
    def _is_closed(self, conn):
        try:
            conn.ping()
            return False
        except Exception:
            return True

    def _can_reuse(self, conn):
        try:
            conn.ping()
            return True
        except Exception:
            return False


class OracleMigrator(SchemaMigrator):
    # 定制开发：Wanbo 20250415
    def _alter_table(self, table, operation):
        statement = f'ALTER TABLE "{table.upper()}" {operation}'
        cursor = self.database.cursor()
        try:
            cursor.execute(statement)
            self.database.commit()
        except Exception:
            logger.exception("Oracle ALTER TABLE failed: %s", statement)
            self.database.rollback()
            raise

    @staticmethod
    def _field_to_type(field):
        if isinstance(field, CharField):
            return f"VARCHAR2({field.max_length or 255})"
        field_type = getattr(field, "field_type", None) or field.get_db_field()
        mapping = OracleDatabase.field_types
        return mapping.get(field_type, field_type)

    def add_column(self, table, column_name, field):
        operation = f'ADD "{column_name.upper()}" {self._field_to_type(field)}'
        if field.default is not None:
            default = field.default() if callable(field.default) else field.default
            if isinstance(default, (dict, list)):
                default = json.dumps(default)
            if isinstance(default, str):
                operation += f" DEFAULT '{default}'"
            else:
                operation += f" DEFAULT {default}"
        if not field.null:
            operation += " NOT NULL"
        self._alter_table(table, operation)

    def alter_column_type(self, table, column_name, field):
        operation = f'MODIFY "{column_name.upper()}" {self._field_to_type(field)}'
        self._alter_table(table, operation)

    def drop_column(self, table, column_name, cascade=True):
        operation = f'DROP COLUMN "{column_name.upper()}"'
        if cascade:
            operation += " CASCADE CONSTRAINTS"
        self._alter_table(table, operation)

    def rename_column(self, table, old_name, new_name):
        self._alter_table(table, f'RENAME COLUMN "{old_name.upper()}" TO "{new_name.upper()}"')
