show pdbs;
ALTER SYSTEM SET PROCESSES=500 SCOPE=SPFILE; 
alter session set container=freepdb1;
create user conrag identified by conrag DEFAULT TABLESPACE users quota unlimited on users;
grant DB_DEVELOPER_ROLE to conrag;

create user ragvector identified by ragvector DEFAULT TABLESPACE users quota unlimited on users;
grant DB_DEVELOPER_ROLE to ragvector;

BEGIN
CTX_DDL.CREATE_PREFERENCE('my_chinese_vgram_lexer','CHINESE_VGRAM_LEXER');
END;
/
